version: '3'

services:
  redis:
    image: redis:3-alpine
    ports:
      - 6379
  sentinel:
    build: ./sentinel/3-alpine
    depends_on:
      - redis
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - MASTER_HOST=dockerredis_redis_1
  redisproxy:
    build: ./haproxy/1.7
    depends_on:
      - redis
      - sentinel
    ports:
      - '9000:9000'
      - '6379:6379'
      - '26379:26379'
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
      - REDIS_HOSTS=dockerredis_redis_1,dockerredis_redis_2,dockerredis_redis_3
      - SENTINEL_HOSTS=dockerredis_sentinel_1,dockerredis_sentinel_2,dockerredis_sentinel_3
      - SENTINEL_NAME=127.0.0.1
      - SENTINEL_PORT=26379
networks:
  default:
    external:
      name: redisha
